package mvc.swagger;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table SA.IOT_DATA
 */
public class IotDataVo {


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SA.IOT_DATA.SAMPLING_TIME
     *
     * @mbg.generated
     */
    private Date sampling_time;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SA.IOT_DATA.EQUIP_ID
     *
     * @mbg.generated
     */
    private BigDecimal equip_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SA.IOT_DATA.EQUIP_TYPE_ID
     *
     * @mbg.generated
     */
    private BigDecimal equip_type_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SA.IOT_DATA.MONITOR_ID
     *
     * @mbg.generated
     */
    private BigDecimal monitor_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SA.IOT_DATA.MANAGER_ID
     *
     * @mbg.generated
     */
    private BigDecimal manager_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SA.IOT_DATA.SENSOR_DATA
     *
     * @mbg.generated
     */
    private String sensor_data;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SA.IOT_DATA.DATA_TYPE
     *
     * @mbg.generated
     */
    private String data_type;

    public Date getSampling_time() {
        return sampling_time;
    }

    public void setSampling_time(Date sampling_time) {
        this.sampling_time = sampling_time;
    }

    public BigDecimal getEquip_id() {
        return equip_id;
    }

    public void setEquip_id(BigDecimal equip_id) {
        this.equip_id = equip_id;
    }

    public BigDecimal getEquip_type_id() {
        return equip_type_id;
    }

    public void setEquip_type_id(BigDecimal equip_type_id) {
        this.equip_type_id = equip_type_id;
    }

    public BigDecimal getMonitor_id() {
        return monitor_id;
    }

    public void setMonitor_id(BigDecimal monitor_id) {
        this.monitor_id = monitor_id;
    }

    public BigDecimal getManager_id() {
        return manager_id;
    }

    public void setManager_id(BigDecimal manager_id) {
        this.manager_id = manager_id;
    }

    public String getSensor_data() {
        return sensor_data;
    }

    public void setSensor_data(String sensor_data) {
        this.sensor_data = sensor_data;
    }

    public String getData_type() {
        return data_type;
    }

    public void setData_type(String data_type) {
        this.data_type = data_type;
    }

    public IotDataVo(Date sampling_time, BigDecimal equip_id, BigDecimal equip_type_id, BigDecimal monitor_id, BigDecimal manager_id, String sensor_data, String data_type) {
        this.sampling_time = sampling_time;
        this.equip_id = equip_id;
        this.equip_type_id = equip_type_id;
        this.monitor_id = monitor_id;
        this.manager_id = manager_id;
        this.sensor_data = sensor_data;
        this.data_type = data_type;
    }

    @Override
    public String toString() {
        return "IotDataVo{" +
                "sampling_time=" + sampling_time +
                ", equip_id=" + equip_id +
                ", equip_type_id=" + equip_type_id +
                ", monitor_id=" + monitor_id +
                ", manager_id=" + manager_id +
                ", sensor_data='" + sensor_data + '\'' +
                ", data_type='" + data_type + '\'' +
                '}';
    }
}